name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    services:
      postgres:
        # note that ubuntu-22.04 come with postgresql-client-14
        # and that test relies on PostGIS extension
        image: postgis/postgis:14-3.4
        env:
          POSTGRES_PASSWORD: ChangeIt
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432

    strategy:
      matrix:
        node-version: [18.x,20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install PostgreSQL client
      run: |
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends postgresql-client

    - name: Run tests
      run: |
        createdb gis
        npm test
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: postgres
        PGPASSWORD: ChangeIt
        PGDATABASE: gis

    # - name: Publish coverage to coveralls.io
    #   run: npm run coveralls
    #   if: github.ref == 'refs/heads/master' && matrix.node-version == '20.x'
    #   env:
    #     COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

